#!/bin/sh
#
# Copyright (C) 2010 Denis Roio <jaromil@nimk.nl>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

APPROOT=/apps/hdsync/

USBROOT=`mount | awk '/.tmp.mnt/ { print $3}'`

if ! [ -r $USBROOT/hdsync.conf ]; then
    echo "config file not found" > /tmp/hdsync.log
    echo "place hdsync.conf in your usb key" >> /tmp/hdsync.log
    exit 0
else
# source settings
    . $USBROOT/hdsync.conf
    echo "config file found in $USBROOT/hdsync.conf" > $SYNC_LOG
    echo "sync role configured to: $SYNC_ROLE" >> $SYNC_LOG
fi

export APPROOT
export SYNC_LOG
export OFFER_SLEEP
export ETH_IFACE

# load up utils
. /apps/hdsync/bin/utils-sync.sh

if [ "x$VIDEO_OUT" != "xdefault" ]; then
    # wait the boot to complete
    sleep 15
    switch_output $VIDEO_OUT
fi

if [ "x$SYNC_ROLE" = "xoffer" ]; then
    $APPROOT/bin/offer-sync.sh eth0 >> $SYNC_LOG
else
    $APPROOT/bin/listen-sync.sh eth0 >> $SYNC_LOG
fi
