#!/bin/sh
#
# Copyright (C) 2010-2011 Denis Roio <jaromil@nimk.nl>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# wait the boot to complete

APPROOT=/apps/hdsync

if [ "$1" = "stop" ]; then
    UPNPPORT="`lsof -a -i4 -sTCP:LISTEN -c DMARender -F n | awk -v FS=':' '/^n/ {print $2}'`"
    $APPROOT/bin/avremote -p $UPNPPORT stop
    rm -f /tmp/hdsync.reply
    umount /apps/hdsync
    exit 0
fi

sleep 15


touch /tmp/hdsync.log
# USBROOT=`mount | awk '/.tmp.mnt/ { print $3}'`
USBROOT=`cat /tmp/appsRoot | grep hdsync | sed 's/hdsync//`
echo "HDSync app running on USB $USBROOT" >> /tmp/hdsync.log
date >> /tmp/hdsync.log
echo "args: $@" >> /tmp/hdsync.log

# if there is a custom osd, we have to wait longer
ls $USBROOT/ | grep 'osd.bin$'
if [ $? = 0 ]; then
    sleep 15
fi

if ! [ -r $USBROOT/hdsync.conf ]; then
    echo "config file not found" >> /tmp/hdsync.log
    echo "place hdsync.conf in your usb key" >> /tmp/hdsync.log
    exit 0
else
# source settings
    . $USBROOT/hdsync.conf
    echo "config file found in ${USBROOT}hdsync.conf" >> /tmp/hdsync.log
fi

export USBROOT
export APPROOT
export HDSYNC_NETWORK
export HDSYNC_CHANNEL
export HDSYNC_SLEEP
export TOTAL_CHANNELS

# load up utils
. $APPROOT/bin/utils-sync.sh

# retrieve network details
get_ip

# retrieve application details
get_bins $APPROOT

if [ $HDSYNC_SLEEP ]; then
    echo "SLEEP adjust set to $HDSYNC_SLEEP seconds" >> /tmp/hdsync.log
fi

UPNPPORT="`lsof -a -i4 -sTCP:LISTEN -c DMARender -F n | awk -v FS=':' '/^n/ {print $2}'`"
export UPNPPORT
echo "UPNP port detected listening on $UPNPPORT" >> /tmp/hdsync.log
# this exports UPNPPORT if a UPNP daemon is found listening

# wait that the usb is mounted
sleep 10

# will get ready for play button
prepare_play >> /tmp/hdsync.log

if [ "$HDSYNC_CHANNEL" = "1" ]; then
    echo "Offering sync" >> /tmp/hdsync.log
    $APPROOT/bin/offer-sync.sh >> /tmp/hdsync.log
else
    echo "Listening for sync offers" >> /tmp/hdsync.log
    $APPROOT/bin/listen-sync.sh >> /tmp/hdsync.log
fi
