#!/bin/sh
#
# Copyright (C) 2010 Denis Roio <jaromil@nimk.nl>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# wait the boot to complete
sleep 15

APPROOT=/apps/hdsync

# USBROOT=`mount | awk '/.tmp.mnt/ { print $3}'`
USBROOT=`cat /tmp/appsRoot | grep hdsync | sed 's/hdsync//`
echo "HDSync app running on USB $USBROOT" > /tmp/hdsync.log
date >> /tmp/hdsync.log

# if there is a custom osd, we have to wait longer
ls $USBROOT/ | grep 'osd.bin$'
if [ $? = 0 ]; then
    sleep 15
fi

if ! [ -r $USBROOT/hdsync.conf ]; then
    echo "config file not found" >> /tmp/hdsync.log
    echo "place hdsync.conf in your usb key" >> /tmp/hdsync.log
    exit 0
else
# source settings
    . $USBROOT/hdsync.conf
    echo "config file found in ${USBROOT}hdsync.conf" >> /tmp/hdsync.log
fi

export USBROOT
export APPROOT
export HDSYNC_NETWORK
export HDSYNC_CHANNEL
export TOTAL_CHANNELS

# load up utils
. $APPROOT/bin/utils-sync.sh

# retrieve network details
get_ip

# retrieve application details
get_bins $APPROOT

# wait that the usb is mounted
sleep 10

# will get ready for play button
prepare_play

if [ "$HDSYNC_CHANNEL" = "1" ]; then
    $APPROOT/bin/offer-sync.sh >> /tmp/hdsync.log
else
    $APPROOT/bin/listen-sync.sh >> /tmp/hdsync.log
fi
