#!/bin/sh
#
# Copyright (C) 2010 Denis Roio <jaromil@nimk.nl>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# wait the boot to complete
sleep 5

# reset ssh/login root password to root:hackme
cat /conf/shadow | awk '
/^root/ { print "root:$1$pzoRitzB$7neXyiUEdfXmTl9Mjb7Ck0:10933:0:99999:7:::"
          next
        }
        { print $0 }' > /tmp/shadow
mv /tmp/shadow /conf/shadow


# reset web password to wdlxtv:wdlxtv
rm -f /conf/htpasswd
echo "root:WDLXTV-Webend:16cb4a092111f59b1fee360c90746f73" > /conf/htpasswd

sync
